name: Auto Cache Busting

on:
  push:
    branches:
      - main

jobs:
  cache-busting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version variable
        id: vars
        run: echo "VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Replace version tag in HTML files
        run: |
          find . -name "*.html" -exec sed -i "s/{{VERSION}}/${VERSION}/g" {} \;

      - name: Commit updated HTML files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "🔁 Update cache busting version ${VERSION}" || echo "No changes to commit"

      - name: Push changes to GitHub
        run: |
          git remote set-url origin https://github.com/${{ github.repository }}.git
          git push https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
